apiVersion: v1
kind: Service
metadata:
  name: npsvc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: mywebport
      protocol: TCP
      port: 1234
      targetPort: 5000
      nodePort: 30007
      protocol: TCP
