apiVersion: v1
kind: ReplicationController
metadata:
  name: "myrc1"
spec:
  replicas: 1
  selector:
    app: "myapp"
  template:
    metadata:
      name: "mypod1"
      labels:
        app: "myapp"
    spec:
      containers:
      - name: "c1"
        image: "adashd/myapp:v1"
